### PR TITLE
Introduce LRU cache for RVC

### PR DESCRIPTION
**Pull request by Paladinium**
### Context
The current RVC implementation re-creates the VC object on each invocation. Since this requires loading the model and training the FAISS index, it leads to a runtime penalty. For usages of the REST API implementing real-time voice cloning, this is a blocker for using RVC.

### Solution
Cache both, the creation of the VC (1 cache entry per voice model) as well as loading the Hubert model.

No efforts were made to pre-load RVC voice models, which means that the 1st invocation still requires some time.

### Implications
Some `global` variables had to be made local in order to avoid interferences between different models, which is [in general a good practice](https://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-so-evil).

### Example
First invocation:
```
[AllTalk GEN] Ask not what your country can do for you, but what you can do for your country.
[AllTalk GEN] TTS Generate: 1.23 seconds. LowVRAM: False DeepSpeed: True
[AllTalk GEN] RVC Convert : Model: model.pth Index: added_IVF1221_Flat_nprobe_1_John_Fitzgerald_Kennedy_v2.index
[AllTalk GEN] RVC Convert : 3.50 seconds. Method: rmvpe Index size used 45000
```

2nd invocation:
```
[AllTalk GEN] Ask not what your country can do for you, but what you can do for your country.
[AllTalk GEN] TTS Generate: 0.90 seconds. LowVRAM: False DeepSpeed: True
[AllTalk GEN] RVC Convert : Model: model.pth Index: added_IVF1221_Flat_nprobe_1_John_Fitzgerald_Kennedy_v2.index
[AllTalk GEN] RVC Convert : 0.32 seconds. Method: rmvpe Index size used 45000
```
Saving 3.18s for RVC conversion in this example (or 90%).

### Open questions
- Should caching be configurable? If yes, this would require [manual implementations](https://www.datacamp.com/tutorial/python-cache-introduction) for cache handling. Recommendation: Implement caching config options when needed instead of upfront.
- Should RVC models been preloaded? Recommendation: Yes, but in a separate MR. Also, a config option would be recommended.

### CODE REVIEW

**Comment by erew123** [comment]
Hi @Paladinium This looks awesome! :) I have a few days free now to catch up on my own life bits and also to start taking a look at Github/AllTalk. Im going to try getting through the support requests etc first and then Ill be taking a look at PR's and other code changes. I suspect I may have some package updating to do over the next few days, which may take a while.

I will take a look though and get back to you about this :) Just thought id give you a holding email, letting you know Ive seen the PR is here :)

Thanks

**Comment by erew123** [comment]
Hi @Paladinium Ive tried this out! Its great!

Here are a couple of thoughts (though I will import it now anyway).

We should probably include a max amount of models to cache in memory e.g.

``@lru_cache(maxsize=3)``

That would stop memory creep if people are loading/unloading lots of different RVC models. The oldest used model would be over-written when the next rvc model is loaded, so maintaining only 3 models max stored in ram. I guess 3 would be a reasonable sweet spot? 

I could quite easily add something to move the model between cuda<>system ram if needed to free GPU memory on low vram situations (would probably add about 0.5 of a second max to generations).

Re **Should RVC models been preloaded? Recommendation: Yes, but in a separate MR. Also, a config option would be recommended.** are you proposing that maybe on start-up of alltalk, there would be a automatic loading of a selection of RVC voices ready to go?

what do you think?

**Comment by erew123** [comment]
@Paladinium also bumped this explainer into the WIKI https://github.com/erew123/alltalk_tts/wiki/RVC-(Retrieval%E2%80%90based-Voice-Conversion)#model-caching

**Comment by Paladinium** [comment]
@erew123 Thanks for merging this change. Regarding your questions:

- _"We should probably include a max amount of models to cache in memory"_
  - OK, I'll have a look at it. But I would suggest to make it configurable then: It might depend on your hardware and use-case how many models you want to cache. Default would be 3 as suggested by you.
- _"Are you proposing that maybe on start-up of alltalk, there would be a automatic loading of a selection of RVC voices ready to go?"
  - Yes. Depending on the requirements you have, you might want alltalk to have fast response times even when accessing a model for the 1st time. Default would be to not preload any model to reflect the current behavior.

**Comment by S-T-K** [comment]
Had an issue with batch rvc processing locally, my vram was running out after a while.
Noticed that the maxsize suggested here was never added, at least I couldn't find it.
After adding it myself, the issue was fixed.

**Comment by Paladinium** [comment]
@S-T-K : You are right. The limit was never implemented.

If you fixed it, would you mind creating a pull request so that others can also benefit from it?

**Comment by S-T-K** [comment]
@Paladinium 
Probably one of the smallest pull requests ever, but done

**Pull request merged**
